github_url: https://github.com/indieSoftware/INCoreData
author: indie-Software
theme: fullwidth
title: INCoreData
module: INCoreData
clean: true
output: ./docs
readme: README.md
skip_undocumented: false
hide_documentation_coverage: false
min_acl: public
sdk: iphone
objc: false
swift_build_tool: xcodebuild
xcodebuild_arguments:
  - build
  - -workspace
  - INCoreData.xcworkspace
  - -scheme
  - INCoreData
  - -destination
  - platform=iOS Simulator,OS=latest,name=iPhone 13
